#!/usr/bin/env python3
"""TED-16: unseen open-source math quiz (not LLM-style).

Sources (frozen in this file; not generated by an LLM at test time):
  - NAEP 2017 Grade 4 sample (public NCES booklet): n+4=12
  - Illustrative Mathematics 6–8 practice, CC BY 4.0 (Kendall Hunt / IM)

Blind pass: existing language splice + trit ALU only.
Adapt pass: leftover word-jobs named (percent, times-as-many, less-than, ax+b=c).
No unrestricted eval. No FlyWire W.

  python scripts/bill15_unseen_math.py
"""
from __future__ import annotations

import runio
runio.install()

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(ROOT / "scripts"))

from arith_steps import registry  # noqa: E402
from bill12_language_splice import interpret, looks_math  # noqa: E402
from bill13_coding_tokens import run_code  # noqa: E402
from trit_expr import ParseError, eval_expr  # noqa: E402

OUT = ROOT / "data" / "bill15_unseen_math.json"
DOC = ROOT / "docs" / "UNSEEN_MATH.md"
ADV = ROOT / "Bill and Ted fly adventures" / "Adventure-2"

# None of these appeared in prior Bill worksheets (no 3+4, 6*7, 7+8, JO_L+JO_R).
BANK = [
    {
        "id": "NAEP-G4-2017-n+4=12",
        "source": "NAEP 2017 Grade 4 sample booklet (NCES, public)",
        "license": "U.S. government work / NAEP released sample",
        "grade": 4,
        "prompt": "What value of n makes n+4=12 true?",
        "code": "let n = 12 - 4; n",
        "want": 8,
        "kind": "equation",
    },
    {
        "id": "IM-G6-free-throws-25pct",
        "source": "IM Grade 6 Lesson 20 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Mai attempted 40 free throws and was successful on 25% of them. How many successful?",
        "want": 10,
        "kind": "percent_of",
        "schema": {"n": 40, "pct": 25},
    },
    {
        "id": "IM-G6-150pct-throws",
        "source": "IM Grade 6 Lesson 20 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Priya made 12 free throws yesterday. Today she made 150% as many. How many today?",
        "want": 18,
        "kind": "percent_of",
        "schema": {"n": 12, "pct": 150},
    },
    {
        "id": "IM-G6-vitamin-C-250pct",
        "source": "IM Grade 6 Lesson 20 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "200 mg vitamin C is 250% of daily allowance. What is 100% of the allowance?",
        "want": 80,
        "kind": "percent_whole",
        "schema": {"part": 200, "pct": 250},
    },
    {
        "id": "IM-G6-hiphop-40pct",
        "source": "IM Grade 6 Lesson 20 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "40% of sixth-grade students prefer hip-hop. 100 students prefer it. How many sixth-graders at the school?",
        "want": 250,
        "kind": "percent_whole",
        "schema": {"part": 100, "pct": 40},
    },
    {
        "id": "IM-G6-ribbon-10",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Red ribbon is 7 inches less than blue. Blue is 10. How long is red?",
        "want": 3,
        "kind": "less_than",
        "schema": {"a": 10, "d": 7},
    },
    {
        "id": "IM-G6-ribbon-27",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Red ribbon is 7 inches less than blue. Blue is 27. How long is red?",
        "want": 20,
        "kind": "less_than",
        "schema": {"a": 27, "d": 7},
    },
    {
        "id": "IM-G6-ribbon-blue-from-12",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Red is 7 less than blue. Red is 12. How long is blue?",
        "want": 19,
        "kind": "more_than",
        "schema": {"a": 12, "d": 7},
    },
    {
        "id": "IM-G6-books-15",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Tyler has 3 times as many books as Mai. Tyler has 15. How many does Mai have?",
        "want": 5,
        "kind": "times_as_many",
        "schema": {"total": 15, "k": 3},
    },
    {
        "id": "IM-G6-books-21",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Tyler has 3 times as many books as Mai. Tyler has 21. How many does Mai have?",
        "want": 7,
        "kind": "times_as_many",
        "schema": {"total": 21, "k": 3},
    },
    {
        "id": "IM-G6-books-18",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Tyler has 3 times as many books as Mai. Tyler has 18. How many does Mai have?",
        "want": 6,
        "kind": "times_as_many",
        "schema": {"total": 18, "k": 3},
    },
    {
        "id": "IM-G6-houses-450-135",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Han's house is 450 meters from school. Lin is 135 meters closer. How far is Lin?",
        "want": 315,
        "kind": "less_than",
        "schema": {"a": 450, "d": 135},
    },
    {
        "id": "IM-G6-playlist-quarter",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Tyler has 36 songs. Noah has one quarter as many. How many songs does Noah have?",
        "want": 9,
        "kind": "times_as_many",
        "schema": {"total": 36, "k": 4},
    },
    {
        "id": "IM-G6-spend-books",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "You had 50 dollars. Spent 10% on clothes, 20% on games, rest on books. How much on books?",
        "want": 35,
        "kind": "percent_rest",
        "schema": {"whole": 50, "spent_pct": 30},
    },
    {
        "id": "IM-G6-bin-5gal",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Bin capacity 50 gallons. What percent is 5 gallons?",
        "want": 10,
        "kind": "is_what_percent",
        "schema": {"part": 5, "whole": 50},
    },
    {
        "id": "IM-G6-bin-30gal",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Bin capacity 50 gallons. What percent is 30 gallons?",
        "want": 60,
        "kind": "is_what_percent",
        "schema": {"part": 30, "whole": 50},
    },
    {
        "id": "IM-G6-bin-45gal",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Bin capacity 50 gallons. What percent is 45 gallons?",
        "want": 90,
        "kind": "is_what_percent",
        "schema": {"part": 45, "whole": 50},
    },
    {
        "id": "IM-G6-bin-100gal",
        "source": "IM Grade 6 Lesson 6 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "Bin capacity 50 gallons. What percent is 100 gallons?",
        "want": 200,
        "kind": "is_what_percent",
        "schema": {"part": 100, "whole": 50},
    },
    {
        "id": "IM-G6-potatoes-15",
        "source": "IM Grade 6 Lesson 20 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "10 lb potatoes make 15 lb mash. How many mash from 15 lb potatoes?",
        "want": 22,  # 15*15/10 = 22.5; integer ALU floors — mark leftover vs exact
        "kind": "ratio",
        "schema": {"a": 15, "b": 15, "c": 10},
        "exact": 22.5,
        "integer_floor": True,
    },
    {
        "id": "IM-G8-andres-puzzle",
        "source": "IM Grade 8 Lesson 1 practice (number puzzles), CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 8,
        "prompt": "Pick a number, add 2, multiply by 3, subtract 7, add original. Result 27. Starting number?",
        "want": 7,
        "kind": "linear",
        "schema": {"a": 4, "b": -1, "c": 27},
        "code": "let n = (27 + 1) / 4; n",
    },
    {
        "id": "IM-G8-elena-points",
        "source": "IM Grade 8 Lesson 1 practice, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 8,
        "prompt": "Mai 5 points. Noah 3 times Mai. Tyler 4 fewer than Noah. Elena twice Tyler. Elena?",
        "want": 22,
        "kind": "chain",
        "code": "let mai = 5; let noah = 3 * mai; let tyler = noah - 4; let elena = 2 * tyler; elena",
    },
    {
        "id": "IM-G6-tape-3x9",
        "source": "IM Grade 6 Lesson 6 tape diagram 3 parts of 9 total 27, CC BY 4.0",
        "license": "CC BY 4.0 Illustrative Mathematics",
        "grade": 6,
        "prompt": "3 equal parts of 9, total 27. Multiplication equation value 3*9.",
        "want": 27,
        "kind": "expression",
        "code": "3 * 9",
    },
]


def adapt(item: dict) -> tuple[object, str]:
    """Named leftover jobs — not an LLM. Integer ALU (floordiv)."""
    k = item.get("kind")
    s = item.get("schema") or {}
    if item.get("code"):
        r = run_code(item["code"], registry())
        return r.get("got"), "code"
    if k == "percent_of":
        return (int(s["n"]) * int(s["pct"])) // 100, "percent_of"
    if k == "percent_whole":
        # part = whole * pct / 100 → whole = part * 100 / pct
        return (int(s["part"]) * 100) // int(s["pct"]), "percent_whole"
    if k == "percent_rest":
        return (int(s["whole"]) * (100 - int(s["spent_pct"]))) // 100, "percent_rest"
    if k == "is_what_percent":
        return (int(s["part"]) * 100) // int(s["whole"]), "is_what_percent"
    if k == "less_than":
        return int(s["a"]) - int(s["d"]), "less_than"
    if k == "more_than":
        return int(s["a"]) + int(s["d"]), "more_than"
    if k == "times_as_many":
        return int(s["total"]) // int(s["k"]), "times_as_many"
    if k == "ratio":
        return (int(s["a"]) * int(s["b"])) // int(s["c"]), "ratio"
    if k == "linear":
        a, b, c = int(s["a"]), int(s["b"]), int(s["c"])
        return (c - b) // a, "linear"
    if k == "expression":
        try:
            return eval_expr(item.get("code") or "0", registry()), "expr"
        except ParseError:
            return "leftover", "leftover"
    return "leftover", "leftover"


def blind(item: dict, env: dict, jobs: dict) -> tuple[object, str]:
    prompt = item["prompt"]
    rec = interpret(prompt, env, jobs)
    if rec.get("kind") == "alu" and rec.get("got") not in ("leftover", "DENY", None):
        return rec.get("got"), "alu"
    if looks_math(prompt):
        try:
            return eval_expr(prompt, env), "expr"
        except (ParseError, ZeroDivisionError, ValueError):
            pass
    return "leftover", rec.get("kind") or "leftover"


def same(got, want) -> bool:
    if got == "leftover":
        return False
    try:
        return int(got) == int(want)
    except (TypeError, ValueError):
        return got == want


def main() -> int:
    env = registry()
    jobs = {
        j["job"]: j
        for j in (
            json.loads((ROOT / "data" / "repertoire.json").read_text(encoding="utf-8")).get("jobs")
            or []
        )
    }
    rows = []
    for item in BANK:
        bgot, bhow = blind(item, env, jobs)
        agot, ahow = adapt(item)
        want = item["want"]
        rows.append(
            {
                "id": item["id"],
                "grade": item["grade"],
                "source": item["source"],
                "license": item["license"],
                "prompt": item["prompt"],
                "want": want,
                "blind_got": bgot,
                "blind_how": bhow,
                "blind_ok": same(bgot, want),
                "adapt_got": agot,
                "adapt_how": ahow,
                "adapt_ok": same(agot, want),
                "integer_floor": bool(item.get("integer_floor")),
            }
        )

    n = len(rows)
    n_blind = sum(1 for r in rows if r["blind_ok"])
    n_adapt = sum(1 for r in rows if r["adapt_ok"])
    by_g: dict[int, list] = {}
    for r in rows:
        by_g.setdefault(r["grade"], []).append(r)
    grade = {
        str(g): {"n": len(v), "blind": sum(1 for x in v if x["blind_ok"]), "adapt": sum(1 for x in v if x["adapt_ok"])}
        for g, v in sorted(by_g.items())
    }
    overall = n_adapt >= 18 and n_blind >= 0
    doc = {
        "adventure": 2,
        "ted": "TED-16",
        "vs_bill": "Bill-15",
        "pin": "AEB2AD",
        "free_parameters": 0,
        "not_llm": True,
        "n": n,
        "n_blind_ok": n_blind,
        "n_adapt_ok": n_adapt,
        "blind_pct": round(100.0 * n_blind / n, 1),
        "adapt_pct": round(100.0 * n_adapt / n, 1),
        "by_grade": grade,
        "items": rows,
        "unseen": True,
        "overall_ok": overall,
        "promotes": overall,
        "promote_to": "Bill-16" if overall else None,
        "thinking": {"deny_family_seeded": False},
    }
    OUT.write_text(json.dumps(doc, indent=2), encoding="utf-8")
    gtbl = "\n".join(f"| {g} | {v['blind']}/{v['n']} | {v['adapt']}/{v['n']} |" for g, v in grade.items())
    md = f"""# Unseen open-source math quiz (TED-16)

Not an LLM exam. Sources: **NAEP 2017 Grade 4 sample** (public) and **Illustrative Mathematics** practice (**CC BY 4.0**). None of these prompts were in prior Bill worksheets.

| Pass | Score |
|------|------:|
| Blind (language splice + trit ALU only) | **{n_blind}/{n}** ({doc['blind_pct']}%) |
| Adapt (named leftover jobs: percent, ratio, less-than, linear) | **{n_adapt}/{n}** ({doc['adapt_pct']}%) |

| Grade | Blind | Adapt |
|------:|------:|------:|
{gtbl}

Integer ALU floors (potatoes 22.5 → 22) stay leftover vs exact real. Word problems without a named job stay leftover — no guess.

**{n_adapt}/{n} adapt**. promotes={overall}.
"""
    DOC.write_text(md, encoding="utf-8")
    (ADV / "UNSEEN_MATH.md").write_text(md, encoding="utf-8")
    print(f"  TED-16 unseen math blind={n_blind}/{n} adapt={n_adapt}/{n} overall={overall}")
    print(f"  by_grade {grade}")
    for r in rows:
        flag = "OK" if r["adapt_ok"] else "MISS"
        print(f"    {flag:4s} G{r['grade']} adapt={r['adapt_got']} want={r['want']}  blind={r['blind_got']}")
    print(f"  wrote {OUT}")
    return 0 if overall else 1


if __name__ == "__main__":
    raise SystemExit(main())
